# Generated by Django 5.2.8 on 2025-11-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("booking_id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "booking",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "station_no",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "station",
                "managed": False,
            },
        ),
    ]
